name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            golang 1.19.4

      - name: Add plugin
        run: asdf plugin add goapp .

      - name: Add goapp-prototool plugin
        run: asdf goapp add github.com/uber/prototool/cmd/prototool

      - name: Install prototool v1.10.0
        run: asdf install goapp-prototool v1.10.0

      - name: Test
        run: |
          asdf global goapp-prototool v1.10.0
          prototool version