name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@6844d09b13209e7d2ce3b63d2b089a2acef581ec

      - name: Run ShellCheck
        run: scripts/shellcheck.bash

  shellfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@6844d09b13209e7d2ce3b63d2b089a2acef581ec

      - name: List file to shfmt
        run: shfmt -f .

      - name: Run shfmt
        run: scripts/shfmt.bash

